### PR TITLE
Register @vinkla service provider

### PR DESCRIPTION
**Pull request by vinkla**
You can simply just register the service provider instead of copy/paste the code from the manager class.

### CODE REVIEW

**Comment by vinkla** [comment]
You probably wont need to keep a copy of the configuration file in this repository either. Lets test this and see if you do.

**Comment by vinkla** [comment]
Cool! What about the config files?

**Comment by maxiloc** [comment]
I am going to remove it very soon :)

**Comment by vinkla** [comment]
:+1: Maybe the setup config as well :)

**Comment by maxiloc** [comment]
yep done with commit 14bab7d

**Comment by vinkla** [comment]
Super!

**Pull request merged**
