### PR TITLE
Drop PHP 5.4 and update to 5.5.9

### PR DESCRIPTION
**Pull request by vinkla**
Also dropped the fork of @vinkla's Algolia package.

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Since PHP 5.4 will be “end of life” in September (no more security fixes), Laravel 5.1 LTS will require PHP 5.5+.</p>&mdash; Laravel (@laravel) <a href="https://twitter.com/laravelphp/status/604301486848270336">May 29, 2015</a></blockquote>

### CODE REVIEW

**Comment by vinkla** [comment]
@maxiloc Any update on this?

**Comment by maxiloc** [comment]
For now we do not want to exclude people that are still on 5.0 and php 5.4
Lets see how it evolves. What do you think ?

**Comment by vinkla** [comment]
Since we haven't released any version yet I would drop PHP 5.4 support already. Otherwise you guys gonna need to support it in all current installations for while. 5.4 will end of life in september. I guess in my point of view the best thing is that we will push more users to use more stable and secure versions of PHP. The upgrade from 5.0 to 5.1 is almost none existing. You basically just create a new folder.

**Comment by magnus-bergman** [comment]
I agree with @vinkla :+1:

**Comment by redox** [comment]
LGTM :+1:

**Comment by vinkla** [comment]
Awesome! Thanks :)

**Comment by vinkla** [comment]
Don't forget to remove the algoliasearch-laravel-manager repository.

**Comment by maxiloc** [comment]
@vinkla yes done. Thanks

**Comment by vinkla** [comment]
:+1: 

When will you release the first stable version?

**Comment by maxiloc** [comment]
now !

**Comment by vinkla** [comment]
Awesome! Maybe you could take a look at #15 first?

**Pull request merged**
