### PR TITLE
Add stable version of the testbench package

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by vinkla** [comment]
You're fast :)

**Comment by maxiloc** [comment]
@vinkla Yes I think we are good now. Right ?

**Comment by vinkla** [comment]
I think so. Just let me check one last time.

**Comment by vinkla** [comment]
Maybe we could drop underscores from method names? Example: `_reindex`

**Comment by maxiloc** [comment]
1. No I am not changing this as I want the user to be able to have a reindex function in his model if he want to do some stuff inside
2. Yes done
3. Yes we do not ready need it as this is a very very small project

Yes for docbloc.

**Comment by vinkla** [comment]
1. Then they could just call the parent method `parent::reindex()`. Thats no problem. 
2. Awesome!
3. I think it doesn't matter. It will save you a lot of time when handling PRs and issues.

**Comment by maxiloc** [comment]
1. No as _reindex function is in a Trait
3. Let's see how it evolves. I think we do not need it for now 

Thanks for your feedbacks much appreciated ! :smile:

**Comment by vinkla** [comment]
Anytime! Happy to help :)

**Pull request merged**
