### PR TITLE
Add camelcase convention to variables

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
I did forget to update `EloquentSuscriber` in https://github.com/algolia/algoliasearch-laravel/blob/master/src/EloquentSubscriber.php#L39-L40 Sorry about that!

**Comment by maxiloc** [comment]
Yes no worries, fixed

**Comment by vinkla** [comment]
Good, thanks!

**Pull request merged**
