### PR TITLE
Also look for indices in the indices() method.

### PR DESCRIPTION
**Pull request by joshforbes**
This will allow indices to be computed dynamically when necessary.

### CODE REVIEW

**Comment by joshforbes** [comment]
in ref to https://github.com/algolia/algoliasearch-laravel/issues/90

**Comment by rayrutjes** [comment]
Thanks @joshforbes for this contribution. Sorry about the delay here :/
We haven't forget about this PR but are currently pedal to the metal.

We will come back to this as soon as possible.

**Comment by alexmglover** [comment]
Can this be merged in? I'm bumping up against this right now and need a way to set indices with a method.

**Comment by julienbourdeau** [comment]
Hi @joshforbes,

Thanks for your contribution! 👍  And sorry again for not being able to merge sooner, I hope you understand.

**Comment by joshforbes** [comment]
No worries - thanks for merging!

**Pull request merged**
